### ISSUE TITLE
[FEAT] Config command

### ISSUE THREAD

**Issue by mark-omarov** [trunklabs/gh-contribution-mate#15]
**Description**
A clear and concise description of what you want to 

1) Display a prompt asking for the default commit authoring name, with the default value taken from the global git config.
2) Display a prompt asking for the default commit authoring email address, with the default value taken from the global git config.
3) Add explanations to previous prompts that the user's default name and email will be used for commits, but they can use a different name and/or email address per repository.
4) Handle errors that might occur if the user doesn't have git installed when getting the default author name and email. If this information is unavailable, both previous prompts should be required; otherwise, you can leave them optional.
5) Save the user's configurations as a JSON under the `contrbution-mate` in the configuration directory.
Use [dir](https://deno.land/x/dir@1.5.1) to get the configuration directory location for Linux and Windows.
For macOS, the config directory is under `$HOME/Library/Preferences`, and I don't think it's the correct place for the configuration. It should same as on Linux - under `~/.config/gh-contribution-mate`.
6) Display a selection prompt to create a new sync repository (default name `contribution-mate-sync`).
7) Display each option's repository ID, name, and privacy (public/private).
8) Use color coding to differentiate between public and private repositories in the list.
9) Provide the option to create a new repository and give it a name.
10) Update the configuration file with the repository, notify the user of the saved settings and describe the next steps - to attach local repositories for sync.

**Comment by alexey-marinkevich** [comment]
polish: During the conversation, it was decided to reconsider getting all user's repositories to choose from, when setup the default repository for synchronization. Instead was decided to ask the user to fill the name of an already existing repository, or pass a name for a new one. Then it will prompt to ask if the user wants to add a new repository.

**Comment by mark-omarov** [comment]
Configuration write/read will be done in a separate issue. Closing this one.
