### ISSUE TITLE
[CHORE] Improve deps management

### ISSUE THREAD

**Issue by mark-omarov** [trunklabs/gh-contribution-mate#18]
**Description**

Dev dependencies aren't locked. Instead of using single `deps.ts` we can do `deps.ts` and `devDeps.ts` or something similar.
Would probably make more sense to move them to the root.

**Describe alternatives you've considered**

A clear and concise description of any alternative solutions or features you've
considered.

Not sure if there are alternatives, we will take another look before implementing it.

**Comment by alexey-marinkevich** [comment]
@mark-omarov I agree to use two different deps, one for dev and one for prod packages. But it seems we don't want to use it in our project anymore because of the implementation of the `import_map.json` file instead of them. So we can probably close this issue?

**Comment by mark-omarov** [comment]
@alexey-marinkevich yeah I don't think we need this one anymore.
