### ISSUE TITLE
[BUG] Insufficient validation of repository name

### ISSUE THREAD

**Issue by mark-omarov** [trunklabs/gh-contribution-mate#34]
**Describe the bug**

The repository name for the configuration command needs to be sufficiently validated; we should also use GitHub's repository name rules.

**To Reproduce**

1. `vr dev config`
2. Type `this should not be allowed` in the base repository step.
GitHub doesn't support white spaces and special symbols in repository names.

**Expected behavior**

An error should be shown in the same way we try to input an empty string with spaces.

**Comment by alexey-marinkevich** [comment]
bug: when you try to update the config and when the fields are empty but exist we should add validation to the fields

**Comment by mark-omarov** [comment]
Additionally, `gh repo view` without a name provided will give any repository that found in current dir. This will lead to issues. We need to validate ownership as well.

**Comment by mark-omarov** [comment]
I've created a less specific issue, #39, which will cover validation, and #40, which will cover validation messages.
Because validation should be applied to all fields, not only `repository.`

Also, #42 will cover ownership validation.

@alexey-marinkevich 
> bug: when you try to update the config and when the fields are empty but exist, we should add validation to the fields

This is done as a part of the refactoring in #41.

Closing this issue as a duplicate.
