### ISSUE TITLE
Configure commit-lint for conventional commits

### ISSUE THREAD

**Issue by mark-omarov** [trunklabs/gh-contribution-mate#6]

**Comment by alexey-marinkevich** [comment]
# Research results
* Official documentation doesn't tell you anything about how to use it with deno
* I asked open AI about this, there's its output message:
> To use commitlint with Deno, you will need to install the commitlint module and configure it in your project. The commitlint module is a Deno third-party module that provides a command-line interface (CLI) for running commitlint.
> 
> To install the commitlint module, you can use the following command:
> `deno install --allow-read --allow-run --allow-write --allow-env -f -n commitlint https://deno.land/x/commitlint/cli.ts`
> 
> This will install the commitlint CLI and make it available in your PATH, so you can run it from anywhere on your system.
> 
> Once you have installed the commitlint CLI, you can configure it in your project by creating a commitlint.config.js file in the root of your project. This file should export an object that specifies the configuration options for commitlint.
> 
> For example, you might use the following configuration to enforce a specific commit message format:
> ```
> module.exports = {
>   extends: ['@commitlint/config-conventional'],
>   rules: {
>     'subject-case': [2, 'always', 'lower-case'],
>     'subject-empty': [2, 'never'],
>     'subject-full-stop': [2, 'never', '.'],
>     'type-case': [2, 'always', 'lower-case'],
>     'type-empty': [2, 'never'],
>     'type-enum': [
>       2,
>       'always',
>       ['build', 'ci', 'docs', 'feat', 'fix', 'perf', 'refactor', 'style', 'test'],
>     ],
>   },
> };
> ```
> 
> This configuration specifies that commit messages must include a lowercase subject, a lowercase type, and a type from the specified list of allowed types.
> 
> To run commitlint, you can use the commitlint command followed by the path to the commit message that you want to lint. For example:
> `commitlint -E HUSKY_GIT_PARAMS`
> 
> This will lint the commit message that is currently being prepared by Husky, which is a tool that can be used to run scripts (such as commitlint) as part of the git commit process.

Output isn't a solution at least because we don't have that package in  the denoland database, but can provide some bits of information to help with further research

## Sidenote
During this research found a [parser tool package](https://deno.land/x/commit@0.1.5) for conventional commits, can be useful in the future

**Comment by alexey-marinkevich** [comment]
@mark-omarov I'd be glad to hear your thoughts and comments on this

**Comment by mark-omarov** [comment]
@alexey-marinkevich thanks!
You're right, commitlint isn't available in deno land. Unfortunately, it seems like we don't have an easy solution here, I know we can use npm, but I want to avoid it as much as possible.
We might consider something with velociraptor, those hooks might be useful. As for the commitlint, if deno doesn't have it, we might consider making one. I will take another look later this week or early next week and see what we can do about it. Thanks again!
